# docker-compose.yml
# 作用: 编排和启动所有服务 (后端, 数据库, 前端开发服务器)

version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: taskdiary_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432" # 将容器的5432端口映射到主机的5433，避免与本地PostgreSQL冲突
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskdiary_backend
    env_file: .env # 从根目录的 .env 文件加载环境变量
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app # 挂载代码以实现热重载
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskdiary_frontend
    ports:
      - "5173:5173" # 映射Vite开发服务器端口
    volumes:
      - ./frontend:/app
      - /app/node_modules # 匿名卷，防止主机node_modules覆盖容器中的
    environment:
      # 将API地址注入前端容器, 指向 backend 服务
      - VITE_API_BASE_URL=http://backend:8000/api/v1
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
